site_name: 打工戰士の笔记本
repo_url: https://github.com/zjyinzju/zjyinzju.github.io/
repo_name: zjyinzju
nav:
  - Home: index.md
  - Note:
    - 课程笔记:
      - notes/index.md
      - 数据结构与算法:
        - fds:
          - notes/cs/ds/fds/index.md
          - notes/cs/ds/fds/01.md
          - notes/cs/ds/fds/02.md
          - notes/cs/ds/fds/03.md
          - notes/cs/ds/fds/04.md
          - notes/cs/ds/fds/05.md
          - notes/cs/ds/fds/06.md
          - notes/cs/ds/fds/07.md
          - notes/cs/ds/fds/08.md
          - notes/cs/ds/fds/hw.md
        - ads:
          - notes/cs/ds/ads/index.md
          - notes/cs/ds/ads/avl_skew.md
          - notes/cs/ds/ads/rbt.md
          - notes/cs/ds/ads/heap.md
      - 计算机逻辑设计基础:
        - notes/cs/logic/index.md
        - notes/cs/logic/01.md
        - notes/cs/logic/02.md
        - notes/cs/logic/03.md
      - 数据库系统:
        - notes/cs/db/index.md
        - notes/cs/db/01.md
        - notes/cs/db/02.md
        - notes/cs/db/03.md
        - notes/cs/db/04.md
        - notes/cs/db/05.md
        - notes/cs/db/09.md
        - notes/cs/db/10.md
        - notes/cs/db/11.md
        - notes/cs/db/12.md
        - notes/cs/db/13.md
      - 数学:
        - 离散数学:
          - notes/math/discrete_math/index.md
          - notes/math/discrete_math/01.md
          - notes/math/discrete_math/02.md
          - notes/math/discrete_math/03.md
          - notes/math/discrete_math/04.md
          - notes/math/discrete_math/05.md
          - notes/math/discrete_math/06.md
          - notes/math/discrete_math/08.md
        - 概率论:
          - notes/math/probability/index.md
          - notes/math/probability/C1.md
          - notes/math/probability/C2.md
      - 其他: 
        - notes/others/yu.md 
    - CS:
      - 编程语言:
        - Python: 
          - notes/cs/pl/Python/index.md
          - notes/cs/pl/Python/CS61A.md
        - C++:
          - notes/cs/pl/C++/index.md
          - notes/cs/pl/C++/1.md
      - tools&skills:
        - notes/tools cheatsheet/LaTeX.md
        - notes/tools cheatsheet/shell.md
        - notes/tools cheatsheet/git.md
        - notes/tools cheatsheet/makefile.md
  - other:
    - 记念: other/记念.md
    - 样式记录: other/样式记录.md
theme:
  name: material
  language: zh
  favicon: luoqixi.jpg
  # 页面整体样式，我分了三种
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: test
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: test_dark 
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    admonition:
      info: fontawesome/solid/circle-info
      note: fontawesome/solid/pen-nib
      abstract: fontawesome/solid/list
      tip: fontawesome/solid/key
      success: fontawesome/solid/check
      question: fontawesome/solid/question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/xmark
      danger: fontawesome/solid/virus
      bug: fontawesome/solid/bug
      example: fontawesome/solid/bars
      quote: fontawesome/solid/quote-right

      
  features:
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - toc.follow
    - header.autohide
    - content.code.select
    - content.code.annotate
    - content.code.copy

plugins:
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - index.md
        - link.md
      strict: false
      

markdown_extensions:
  - toc: 
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - tables
  - pymdownx.arithmatex:
      generic: true
  # an extension for to do list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/katex.js
  # - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  # - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css